[package]
name = "runasmidja"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Portable facade for Runasmidja"
publish = false

[lints]
workspace = true

[dependencies]
runasmidja-core = { path = "../runasmidja-core", version = "=0.3.0", default-features = false }
runasmidja-ports = { path = "../runasmidja-ports", version = "=0.3.0", default-features = false }
runasmidja-html = { path = "../runasmidja-html", version = "=0.3.0", default-features = false }
runasmidja-crypto = { path = "../runasmidja-crypto", version = "=0.3.0", default-features = false }
